{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "spark.fullname" . }}
  labels:
    {{- include "spark.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "spark.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    # Allow inter-Spark communication
    - from:
        - podSelector:
            matchLabels:
              {{- include "spark.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.metrics.driver.port }}
        - protocol: TCP
          port: {{ .Values.metrics.executor.port }}
        - protocol: TCP
          port: 7077  # Spark master port
        - protocol: TCP
          port: 7078  # Spark worker port
    # Allow from specified sources
    {{- range .Values.networkPolicy.ingress.from }}
    - from:
        - {{ . | toYaml | nindent 10 }}
      ports:
        - protocol: TCP
          port: {{ $.Values.metrics.driver.port }}
        - protocol: TCP
          port: {{ $.Values.metrics.executor.port }}
    {{- end }}
{{- end }}