{{- if and .Values.serviceAccount.create .Values.rbac.create }}
# Main Airflow RBAC
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "airflow.fullname" . }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "airflow.fullname" . }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "airflow.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "airflow.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
# Worker RBAC for KubernetesExecutor
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "airflow.fullname" . }}-worker
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"] 
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "airflow.fullname" . }}-worker
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "airflow.fullname" . }}-worker
subjects:
  - kind: ServiceAccount
    name: {{ include "airflow.workerServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}