{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "airflow.serviceAccountName" . }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
---
{{- if .Values.rbac.create }}
# Worker Service Account for KubernetesExecutor
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "airflow.workerServiceAccountName" . }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
{{- end }}