apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}-webserver
  labels:
    {{- $component := "webserver" }}
    {{- include "airflow.componentLabels" (dict "Values" .Values "Chart" .Chart "Release" .Release "component" $component) | nindent 4 }}
  annotations:
    {{- include "airflow.metricsAnnotations" . | nindent 4 }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "airflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webserver