{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.secretName" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.database.secretKey }}: {{ include "postgresql.generatePassword" . | b64enc | quote }}
{{- end }}